### ISSUE TITLE
Terminal does not respect shell settings, always using bash

### ISSUE THREAD

**Issue by akariv** [tuzig/terminal7#146]
I tried to change my default shell to use `zsh`, but it stays on bash, and shows this message:
```
The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
bash-3.2$ 
```

Running the chsh command mentioned has no effect.

**Comment by daonb** [comment]
@akariv I just tried to recreate with 0.15.3 and it seems to be fixed. Can you try it again and let me know how it goes?
