### ISSUE TITLE
Sound the bell

### ISSUE THREAD

**Issue by daonb** [tuzig/terminal7#186]
**What's missing? Please describe your flow and where this feature will help.**

The VT100 was ringing its bell on CTRL-G. xtermjs supports it, we just need to pick an audio file and pass it on in `pane.open()`

**Comment by eyal-sasson** [comment]
Found out that if `{ bellStyle: "sound" }` is passed on terminal creation, `t.write("\x07")` (the "terminal bell" Unicode character) does play a sound, though the default sound is a weird knock. We should find a good bell sound, then pass it with `{ bellSound: URI }`.

**Comment by daonb** [comment]
Let's go with the weird knock. Once we have that we can show it to audiophile friends and get their help in picking a sound.
