### ISSUE TITLE
Update the hosts list when peerbook changes

### ISSUE THREAD

**Issue by daonb** [tuzig/terminal7#188]
**Describe the bug**
When I delete peers from my peerbook they are not deleted from the home

**To Reproduce**
1. Launch app
2. go to `pb/terminal7.dev`
3. enter your email
4. get email and click on the link
5. selecet "remove all" and enter your otp
6. go back to terminal7 and get the same peers
7. press peerbook refresh and nothing happens

**Comment by udif** [comment]
Can confirm this, was about to file this myself.

**Comment by udif** [comment]
also, when deleting all peers, it seems to success, but yields an error on top, reading:

`Failed to execute the main template: template: pb.tmpl:83:20: executing "main" at <.Peers>: range can't iterate over`

**Comment by daonb** [comment]
Thanks Udi.

The peerbook bug is at github.com/tuzig/peerbook/issues/25 .

I'm just too busy...
