### ISSUE TITLE
Host settings cannot be re-opened after closing

### ISSUE THREAD

**Issue by eyal-sasson** [tuzig/terminal7#244]
**Describe the bug**
After saving/closing the gate editing form once, it is not possible to open it again.

**To Reproduce**
1. Launch app
2. Long press one of the gates to edit its settings
3. Submit or close the form that was opened
4. Try opening the settings again by long pressing on the gate
5. Settings cannot be opened

**Comment by daonb** [comment]
I failed recreated the bug. I've tried on the iPad app and on Safari & Chrome on the mac.
Can you try it again?
