### ISSUE TITLE
Pane dividers remain after pane close

### ISSUE THREAD

**Issue by daonb** [tuzig/terminal7#247]
**Describe the bug**
Pane dividers are not removed when a pane is close

**To Reproduce**
1. Launch app
2. Connect to a server
3. Split the pane
4. type 'exit'
5. see the divider floating in mid screen

**Comment by eyal-sasson** [comment]
I was not able reproduce this behavior in Chrome on PC: when closing a pane by either 'exit' command or the close button, all the dividers are removed like expected. Does this bug occur on iPad only or on PC too?

**Comment by daonb** [comment]
ItThis is probably a result of an SSH bug. closing.
