### ISSUE TITLE
Make the TUI fit available screen size

### ISSUE THREAD

**Issue by daonb** [tuzig/terminal7#258]
**Describe the bug**
When I edit a gate and the App is a 1/4 of the screen size there's an ugly overflow

**To Reproduce**
1. Launch app
2. Make the App a quarter of the screen wide or 375px wide
3. Long press a gate

**Screenshots**
![IMG_1666](https://user-images.githubusercontent.com/36852/181914886-9b34ebc3-67e9-45c6-a5e9-5a25773e8d44.jpeg)

**Additional context**

**Comment by eyal-sasson** [comment]
Unable to reproduce:
![image](https://user-images.githubusercontent.com/37512471/183288223-04b7f251-d82d-411e-a7bb-bf668a9f91d7.png)
The size of the terminal is correct, though the line wrapping is a bit weird looking.

**Comment by daonb** [comment]
It needs a resize observer to dynamically shrink|grow when the user resizes the screenb
