### ISSUE TITLE
Website should clearly state it's an open source project

### ISSUE THREAD

**Issue by cool-RR** [tuzig/terminal7#270]
When I found the Terminal 7 website, I tried to figure out what it is. Is it a startup? After two minutes of scrolling around, then back up again, I found the GitHub link, followed it and understood that it's an open source project.

It should take 10 seconds, not two minutes. The phrase "open source" doesn't appear even once on the website. In my opinion it should appear either in the title or very close to it.

**Comment by daonb** [comment]
Thanks for the issue. Added open source in the first sentence
