### ISSUE TITLE
Support Cmd-v in t0

### ISSUE THREAD

**Issue by daonb** [tuzig/terminal7#276]
**What's missing? Please describe your flow and where this feature will help.**
I very often copy to the clipboard ip address from other interfaces.
t0 should allow me to paste my data.

**Comment by eyal-sasson** [comment]
Seems like it is supported in map.ts although pasting works in every type of form, but it should only work in the regular one - I think it should be in form.ts.

**Comment by daonb** [comment]
I agree, but it requires some refactoring.

We should first clearly define the relationships between `Terminal7`, `T7Map` & 'Form` and how the state is distributed.
