### ISSUE TITLE
TWR is flashing 

### ISSUE THREAD

**Issue by daonb** [tuzig/terminal7#287]
**Describe the bug**
While inside a gate TWR very rarely starts flashing. It stays small and blinking
and I haven't found a way to make it stop, short of quitting the app.

**To Reproduce**
1. Launch app
2. Tap on '....'
3. ...

**Comment by eyal-sasson** [comment]
Problem is - since px isn't relative, a smaller screen would still suffer from this bug even if the border was thinner.

**Comment by daonb** [comment]
Can't recreate
