### ISSUE TITLE
Fix TWR size & pos in narrow screens

### ISSUE THREAD

**Issue by daonb** [tuzig/terminal7#306]
**Describe the bug**
On narrow screens only a part of TWR is shown. It makes more sense o center 
TWR and grow it up to 90% of narrow screens.

**To Reproduce**
1. Launch app
2. Split screen with a browser
3. Click on TWR

**Screenshots**

![image](https://user-images.githubusercontent.com/36852/198987302-0b7034f2-5e62-467d-a6ce-74ded8d95b3e.jpeg)

**Comment by eyal-sasson** [comment]
Been playing with it for more than an hour now, starting to doubt it's even possible. Fixing t0 to the center requires `position: fixed` but changing from `absolute` to `fixed` cannot have a transition. Not sure what to do...

**Comment by daonb** [comment]
It could be one of this times when we have to use javascript to change css (as we are doing in a few places today). On TWR show, we can calculate the TWR size & pos based on `document.body.offset[Height|Width]' and update the css.

**Comment by eyal-sasson** [comment]
When scrolling left/right, should the TWR still be centered? If so, then even with JS it's not possible since the only way is to use css `fixed`.

**Comment by daonb** [comment]
Good question. 

I believe we should center the map when the TWR is opened. If the user decided to scroll, TWR will stay they save size, but will move from the center together with the map.
