### ISSUE TITLE
When server goes down TWR should get notified

### ISSUE THREAD

**Issue by daonb** [tuzig/terminal7#311]
**Describe the bug**
Today when I shutdown a server, the gate close and I get back to the map
with the TWR minized and no notification. 

We should add a notification "Connection closed by server"

**To Reproduce**
1. Launch app
2. Tap on gate
3. run `sudo shutdown now`

**Comment by eyal-sasson** [comment]
Here's what I'm getting (although through localhost so the behavior may differ):
![image](https://user-images.githubusercontent.com/37512471/203355218-406f55cd-4412-438a-b8c8-220884f6ceab.png)

**Comment by daonb** [comment]
I believe it's solved
