### ISSUE TITLE
Add an hourglass

### ISSUE THREAD

**Issue by daonb** [tuzig/terminal7#320]
**What's missing? Please describe your flow and where this feature will help.**

When the session layer starts a watchdog the user should be able to track its
progress. TWR should add a progress bar to start like:

```
TWR ᗧ·············🍒
```

The PacMan should move right at a constant pace, eating the dots. 
When it gets to the cherry the line will be removed and
the user will get a Timeout message.

**Comment by eyal-sasson** [comment]
@daonb please close this issue as the implementation was merged
