### ISSUE TITLE
Stop the watchdog on ESC

### ISSUE THREAD

**Issue by daonb** [tuzig/terminal7#329]
**Describe the bug**
I opened T7 in the coffeeshop and it opened with my home mac.mini.
As I don't have peerbook install, the re-connect attempt failed and I'm
shown a menu. I choose to reconnect and after a couple of seconds realized 
it's not going to work.

I hit escape and I type `gates` and then start typing `connect moritz` 
only to be interrupted by by a reconnect menu for mini.local

**Screenshots**

**Additional context**
The watchdog today is handled in the session layer and it's
the wron place for it. It should be merged with the hourglass of
[#321] and moved to the shell.

**Comment by eyal-sasson** [comment]
Resolved.
