### ISSUE TITLE
Fix peerbook hosts display on map

### ISSUE THREAD

**Issue by daonb** [tuzig/terminal7#337]
For gates we got from peerbook the expand icon should be replaced with
the address book icon. Clickng the icom willopen https://peerbook.io in
the apps browser.

**Comment by eyal-sasson** [comment]
How would we know if we got a gate from PB? `gate.fp` isn't stored in LocalStorage.

**Comment by daonb** [comment]
peerbook gates comes over the network from peerbook. Whenever T7 connects to pb it gets a list of peers. Checkout `terminal7.onPBMessage` to see how it goes.
