### ISSUE TITLE
Support many, many panes

### ISSUE THREAD

**Issue by daonb** [tuzig/terminal7#342]
**What's missing? Please describe your flow and where this feature will help.**

There's a way to support many more panes.
Instead of creating a webgl context for each pane we need to use a single context
that grows as the user adds more panes.

**Additional context**
This change starts with the xterm-addon-webgl. 
Either we work together the xterm team to upgrade the addon or we change its
interface in a non-breaking way or we'll be forced to copy the addon and work
on a seaprate fork.

**Comment by daonb** [comment]
I opened [an issue over at
xterm.js](https://github.com/xtermjs/xterm.js/issues/4379

**Comment by DmitryPorotov** [comment]
Fixed in https://github.com/tuzig/terminal7/tree/244b3a562f6519dc800cdb3cebd6cf604ac48930

**Comment by daonb** [comment]
Added virtual-webgl2 and it seems to be working
