### ISSUE TITLE
Can't connect to a gate whose name is a suffix of another gate

### ISSUE THREAD

**Issue by daonb** [tuzig/terminal7#347]
**Describe the bug**
I have gate called `mini` that comes from peerbook and a gate called
`mini.local` that was manually defined.When I click "mini" I get an error:
Ambgious gate

**Comment by eyal-sasson** [comment]
Interesting, it didn't happen in my tests... Will have to check again.

**Comment by daonb** [comment]
So you should first write a unit test to validate.

**Comment by daonb** [comment]
I'm on it.
