### ISSUE TITLE
Replace the conf editor with TWR "dotfile" command

### ISSUE THREAD

**Issue by daonb** [tuzig/terminal7#360]
**What's missing? Please describe your flow and where this feature will help.**
I don't like the cogwheels button not going through TWR.
I want it to open TWR and lunch vim with the dotfile in TWR.

**Additional context**

It's probably best to use WASM and compile one of the existing editor.
There's an vim effort which https://github.com/rhysd/vim.wasm is not supported
on mobile browsers.

The best bet is to take simple version, like the original [ex](https://github.com/dlisboa/ex) and compule it to wasm. As it runs inside the TWR terminal it needs no rendering,
just a connection to the terminal write method and keyboard event.

**Comment by eyal-sasson** [comment]
why not just run CodeMirror over xterm.js?

**Comment by davidtheaussie** [comment]
It will be an improvment over what what we have today, but I 'm afraid it'll look strange.Please try it and we' ll see. 
-------- הודעה מקורית --------מאת: Eyal Sasson ***@***.***> תאריך: 29.3.2023  18:35  (GMT+09:00) אל: tuzig/terminal7 ***@***.***> עותק: Subscribed ***@***.***> נושא: Re: [tuzig/terminal7] Replace the conf editor with TWR "dotfile" command (Issue #360) 
why not just run CodeMirror over xterm.js?
