### ISSUE TITLE
The 7 is over the m

### ISSUE THREAD

**Issue by daonb** [tuzig/terminal7#362]
**Describe the bug**
On narrow screens the name looks bad.

**To Reproduce**
1. Launch app
2. make the screen narrow

**Screenshots**
![Image 10-04-2023 at 21 55](https://user-images.githubusercontent.com/36852/230974080-c416adb7-96cd-4425-9642-7aa91f311f5d.jpeg)

**Comment by eyal-sasson** [comment]
I think I'll add a media query to change Terminal7 to T7 on low width.
