### ISSUE TITLE
Improve the `reset` command

### ISSUE THREAD

**Issue by daonb** [tuzig/terminal7#367]
# Current

1. When the user runs the reset command with no gate the command looks for the active gate. If there's non active, the command does nothing and prints "No active connection".
2. "Factory reset" is too wide. Our local storage includes WebRTC Fingerprint, SSH keys, list of gates and first time switches and I want fine grained control

# Improvements

1. Factory Reset will lead to a menu where the user has multiple choices: Fingerprint, SSH keys, Gates and First timer. For each we will print its value (excluding private keys)
2. When the user is currently doing 1, we should replace the message with the new factory reset menu

**Comment by eyal-sasson** [comment]
how does it make sense to reset the fingerprint?

**Comment by daonb** [comment]
@eyal-sasson I sometimes need to erase the fingerprint when testing. It also gives us a great way to present what the local storage holds.

Sorry about the half baked description, I've updated it and the title. Please LMK if you have any questions / ideas for improvements.

**Comment by eyal-sasson** [comment]
Merged.
