### ISSUE TITLE
Remove the prompt printed in the middle of subscribe cmd

### ISSUE THREAD

**Issue by daonb** [tuzig/terminal7#371]
Need to refactor the command to return a Promise and to call resolve() when truly finished.

**Comment by eyal-sasson** [comment]
what prompt? its really hard to test it on the web

**Comment by daonb** [comment]
Look at the code of the subscribe command function and you can see it returns before the operation is completed. We've talked about it briefly last week - we need to return a Prmosie and call resolve only when the command is done.

**Comment by daonb** [comment]
We're talking about the sub command itself. Getting that event is part of
the command flow, so we should reject /resolve until we got the event,
asked the user for his email, print the QR code and validate it.

בתאריך יום ה׳, 1 ביוני 2023, 10:10, מאת Eyal Sasson ‏<
***@***.***>:

**Comment by daonb** [comment]
![image](https://github.com/tuzig/terminal7/assets/36852/a0cd87c6-6b37-4dcf-ba2b-f77581b427a4)
