### ISSUE TITLE
Gate is left half open

### ISSUE THREAD

**Issue by daonb** [tuzig/terminal7#394]
**Describe the bug**
When connected over SSH, swithing to another app and back, dismissing the log and closing the pane using the
lclose pane button, the gate is left half open.

**Screenshots**
![image](https://github.com/tuzig/terminal7/assets/36852/e1cf66d1-4ca2-4ba9-afe8-b7704513eeba)

**Comment by eyal-sasson** [comment]
Doesn't happen anymore - it just brings up the reset gate menu
