### ISSUE TITLE
Change SSH port

### ISSUE THREAD

**Issue by nljackson2020** [tuzig/terminal7#440]
Add the option to change the SSH port per connection.

**Comment by daonb** [comment]
Thanks for the request, it's sure missing. The SSH plugin already support a customs port
but T7 is always calling it with the default `22` port. 

To support a per-gate custom port we need to:
- Store & Load the port number
- Add a `port` field to `editCMD()`
- Load the port number from the properties or `22` in `Terminal7.addGate()`
- Pass the port when intializing an `SSHSession`

**Comment by daonb** [comment]
Done, to be released in 1.9.1
