### ISSUE TITLE
Improve pan handling when using touch (on Win/Android)

### ISSUE THREAD

**Issue by yaelih** [tuzig/terminal7#462]
**Describe the bug**
In some OS (Windows and maybe Android), when moving borders of panes by touch, the movement is limited. Move is cancelled after a short distance. You require to repeat the move again and again.

**To Reproduce**
1. Launch app
2. Split pane to have at least 2 panes
3. Move border by touch  
4. Notice that the border stops moving before the touch of hand stops

**Comment by daonb** [comment]
Thanks for the :bug: It's probably a result of not using hammerjs for these elements. Unfortunately I have limited access to my samsung tablet. Can you take this on?

**Comment by daonb** [comment]
I've played around with it and got two insights:

- hammerjs is no longer maintained so we shouldn't use it anymore
- adding a css rule: `* { touch-action: none; }` fixes this

**Comment by yaelih** [comment]
Ooh.. not so good news regarding hammerjs.
This fix works!!!! :)
You can close this issue
