### ISSUE TITLE
Add ssh client support

### ISSUE THREAD

**Issue by daonb** [tuzig/terminal7#56]
ssh will be used on two occasions:

- when terminal7 connects to a server that has no webexec running, terminal7 should install webexec
- when terminal7 receive an authentication nack, ssh should be used to add the token to webexec's authorised tokens by executing on the server:
`echo <mytoken> >> ~/.webexec/authorized_tokens`

**Comment by daonb** [comment]
should probably use [NMSSH](http://cocoadocs.org/docsets/NMSSH/2.2.7/) to add iOS support to [cordova-plugin-ssh-connect](https://github.com/JosePerez27/cordova-plugin-ssh-connect)

**Comment by erezhod** [comment]
Forked and in development at [tzuig/cordova-plugin-ssh-connect](https://github.com/tuzig/cordova-plugin-ssh-connect).

**Comment by daonb** [comment]
Integrated.
